### ISSUE TITLE
getNumSMS failed with FONA 800 uFL

### ISSUE THREAD

**Issue by king-jam** [adafruit/Adafruit_FONA_Library#46]
Recently purchased a module  and found that:

        if (! sendParseReply(F("AT+CPMS?"), F("\"SM\","), &numsms) ) return -1;
      } else {
        if (! sendParseReply(F("AT+CPMS?"), F("+CPMS: \"SM_P\","), &numsms) ) return -1;
      }
https://github.com/adafruit/Adafruit_FONA_Library/blob/master/Adafruit_FONA.cpp#L483

needs to be changed to:

        if (! sendParseReply(F("AT+CPMS?"), F("\"SM\","), &numsms) ) return -1;
      } else {
        if (! sendParseReply(F("AT+CPMS?"), F("+CPMS: \"SM\","), &numsms) ) return -1;
      }

I don't know the scope of this issue or if I have a one off firmware rev on the SIM800 but might be worth looking into.

**Comment by ladyada** [comment]
do you have a SIM800L or SIM800H? can you check?

**Comment by king-jam** [comment]
Apologies, SIM800H.

**Comment by ladyada** [comment]
mind grabbing the very latest lib ad trying again? we now check for SM_P as well as SM

**Comment by king-jam** [comment]
Tested and verified it is working. Thanks for the fix!
