### ISSUE TITLE
GPS Fix on FONA 3G

### ISSUE THREAD

**Issue by ValentmSTEM** [adafruit/Adafruit_FONA_Library#51]
The GPS test and FONA test 3D location fix hasn't worked for 2 different 3G FONA boards I've purchased (with active antennae). Is this just a code issue with the 3G? The SMS and everything else is working fine. Where are the AT commands given as they aren't in the sketch?

**Comment by ladyada** [comment]
hiya, GPS commands are here
https://github.com/adafruit/Adafruit_FONA_Library/blob/master/Adafruit_FONA.cpp#L717
and the AT command set is here
https://learn.adafruit.com/adafruit-fona-3g-cellular-gps-breakout/downloads
if you are having *tech support* issues please post up on the adafruit tech support forums. thx!

**Comment by OscarVanL** [comment]
Did you manage to get GPS test to work for the Fona 3G?
