### ISSUE TITLE
Serial passthru tunnel only works with some commands

### ISSUE THREAD

**Issue by darrensi** [adafruit/Adafruit_FONA_Library#9]
It appears that only short commands e.g. three characters ones like ATI work. Longer commands e.g. AT+GSN (to get the IMEI) don't work.

**Comment by BrianCJohnson** [comment]
I see the same issue, AT or ATZ works but any AT+... does not work.

**Comment by ladyada** [comment]
yah this is a thing with the serial monitor because it sends full strings at once. 
to fix: use some other serial port monitor rather than the arduino one (which buffers)
we like Putty - works great!

**Comment by BrianCJohnson** [comment]
I implemented a quick hack that seems to work, adding a microsecond delay to the write loop:

    case 'S': {
      Serial.println(F("Creating SERIAL TUBE"));
      while (1) {
        while (Serial.available()) {
          delay(1); // <-- added to get serial tube to work
          fona.write(Serial.read());
        }
        if (fona.available()) {
          Serial.write(fona.read());
        }
      }
      break;
    }
